# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import contacts_pb2 as contacts__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in contacts_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContactsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetContact = channel.unary_unary(
                '/contacts.ContactsService/GetContact',
                request_serializer=contacts__pb2.GetContactRequest.SerializeToString,
                response_deserializer=contacts__pb2.ContactResponse.FromString,
                _registered_method=True)
        self.ListContacts = channel.unary_unary(
                '/contacts.ContactsService/ListContacts',
                request_serializer=contacts__pb2.ListContactsRequest.SerializeToString,
                response_deserializer=contacts__pb2.ListContactsResponse.FromString,
                _registered_method=True)
        self.GetSegmentContacts = channel.unary_unary(
                '/contacts.ContactsService/GetSegmentContacts',
                request_serializer=contacts__pb2.GetSegmentRequest.SerializeToString,
                response_deserializer=contacts__pb2.ListContactsResponse.FromString,
                _registered_method=True)
        self.UpdateHealthScore = channel.unary_unary(
                '/contacts.ContactsService/UpdateHealthScore',
                request_serializer=contacts__pb2.UpdateHealthScoreRequest.SerializeToString,
                response_deserializer=contacts__pb2.HealthScoreResponse.FromString,
                _registered_method=True)
        self.BulkUpsertContacts = channel.unary_unary(
                '/contacts.ContactsService/BulkUpsertContacts',
                request_serializer=contacts__pb2.BulkUpsertRequest.SerializeToString,
                response_deserializer=contacts__pb2.BulkUpsertResponse.FromString,
                _registered_method=True)


class ContactsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSegmentContacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateHealthScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkUpsertContacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContactsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetContact': grpc.unary_unary_rpc_method_handler(
                    servicer.GetContact,
                    request_deserializer=contacts__pb2.GetContactRequest.FromString,
                    response_serializer=contacts__pb2.ContactResponse.SerializeToString,
            ),
            'ListContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContacts,
                    request_deserializer=contacts__pb2.ListContactsRequest.FromString,
                    response_serializer=contacts__pb2.ListContactsResponse.SerializeToString,
            ),
            'GetSegmentContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSegmentContacts,
                    request_deserializer=contacts__pb2.GetSegmentRequest.FromString,
                    response_serializer=contacts__pb2.ListContactsResponse.SerializeToString,
            ),
            'UpdateHealthScore': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateHealthScore,
                    request_deserializer=contacts__pb2.UpdateHealthScoreRequest.FromString,
                    response_serializer=contacts__pb2.HealthScoreResponse.SerializeToString,
            ),
            'BulkUpsertContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.BulkUpsertContacts,
                    request_deserializer=contacts__pb2.BulkUpsertRequest.FromString,
                    response_serializer=contacts__pb2.BulkUpsertResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'contacts.ContactsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('contacts.ContactsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContactsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contacts.ContactsService/GetContact',
            contacts__pb2.GetContactRequest.SerializeToString,
            contacts__pb2.ContactResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contacts.ContactsService/ListContacts',
            contacts__pb2.ListContactsRequest.SerializeToString,
            contacts__pb2.ListContactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSegmentContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contacts.ContactsService/GetSegmentContacts',
            contacts__pb2.GetSegmentRequest.SerializeToString,
            contacts__pb2.ListContactsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateHealthScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contacts.ContactsService/UpdateHealthScore',
            contacts__pb2.UpdateHealthScoreRequest.SerializeToString,
            contacts__pb2.HealthScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkUpsertContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/contacts.ContactsService/BulkUpsertContacts',
            contacts__pb2.BulkUpsertRequest.SerializeToString,
            contacts__pb2.BulkUpsertResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
