# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import intelligence_pb2 as intelligence__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in intelligence_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IntelligenceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetAnalyticsSummary = channel.unary_unary(
                '/intelligence.IntelligenceService/GetAnalyticsSummary',
                request_serializer=intelligence__pb2.AnalyticsRequest.SerializeToString,
                response_deserializer=intelligence__pb2.AnalyticsSummaryResponse.FromString,
                _registered_method=True)
        self.PushInsight = channel.unary_unary(
                '/intelligence.IntelligenceService/PushInsight',
                request_serializer=intelligence__pb2.PushInsightRequest.SerializeToString,
                response_deserializer=intelligence__pb2.PushInsightResponse.FromString,
                _registered_method=True)
        self.GetRevenueForecast = channel.unary_unary(
                '/intelligence.IntelligenceService/GetRevenueForecast',
                request_serializer=intelligence__pb2.ForecastRequest.SerializeToString,
                response_deserializer=intelligence__pb2.ForecastResponse.FromString,
                _registered_method=True)
        self.AskCopilot = channel.unary_unary(
                '/intelligence.IntelligenceService/AskCopilot',
                request_serializer=intelligence__pb2.CopilotRequest.SerializeToString,
                response_deserializer=intelligence__pb2.CopilotResponse.FromString,
                _registered_method=True)


class IntelligenceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetAnalyticsSummary(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushInsight(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRevenueForecast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AskCopilot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IntelligenceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetAnalyticsSummary': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAnalyticsSummary,
                    request_deserializer=intelligence__pb2.AnalyticsRequest.FromString,
                    response_serializer=intelligence__pb2.AnalyticsSummaryResponse.SerializeToString,
            ),
            'PushInsight': grpc.unary_unary_rpc_method_handler(
                    servicer.PushInsight,
                    request_deserializer=intelligence__pb2.PushInsightRequest.FromString,
                    response_serializer=intelligence__pb2.PushInsightResponse.SerializeToString,
            ),
            'GetRevenueForecast': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRevenueForecast,
                    request_deserializer=intelligence__pb2.ForecastRequest.FromString,
                    response_serializer=intelligence__pb2.ForecastResponse.SerializeToString,
            ),
            'AskCopilot': grpc.unary_unary_rpc_method_handler(
                    servicer.AskCopilot,
                    request_deserializer=intelligence__pb2.CopilotRequest.FromString,
                    response_serializer=intelligence__pb2.CopilotResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'intelligence.IntelligenceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('intelligence.IntelligenceService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class IntelligenceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetAnalyticsSummary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intelligence.IntelligenceService/GetAnalyticsSummary',
            intelligence__pb2.AnalyticsRequest.SerializeToString,
            intelligence__pb2.AnalyticsSummaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushInsight(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intelligence.IntelligenceService/PushInsight',
            intelligence__pb2.PushInsightRequest.SerializeToString,
            intelligence__pb2.PushInsightResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRevenueForecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intelligence.IntelligenceService/GetRevenueForecast',
            intelligence__pb2.ForecastRequest.SerializeToString,
            intelligence__pb2.ForecastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AskCopilot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/intelligence.IntelligenceService/AskCopilot',
            intelligence__pb2.CopilotRequest.SerializeToString,
            intelligence__pb2.CopilotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
