# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: intelligence.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'intelligence.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12intelligence.proto\x12\x0cintelligence\"2\n\x10\x41nalyticsRequest\x12\x10\n\x08tenantId\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ys\x18\x02 \x01(\x05\"z\n\x18\x41nalyticsSummaryResponse\x12\x0f\n\x07revenue\x18\x01 \x01(\x01\x12\x0e\n\x06orders\x18\x02 \x01(\x05\x12\x11\n\tcustomers\x18\x03 \x01(\x05\x12\x19\n\x11\x61verageOrderValue\x18\x04 \x01(\x01\x12\x0f\n\x07summary\x18\x05 \x01(\t\"j\n\x12PushInsightRequest\x12\x10\n\x08tenantId\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x10\n\x08severity\x18\x05 \x01(\t\"1\n\x13PushInsightResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"1\n\x0f\x46orecastRequest\x12\x10\n\x08tenantId\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ys\x18\x02 \x01(\x05\"R\n\x10\x46orecastResponse\x12\x18\n\x10predictedRevenue\x18\x01 \x01(\x01\x12\x15\n\rdailyForecast\x18\x02 \x03(\x01\x12\r\n\x05model\x18\x03 \x01(\t\"E\n\x0e\x43opilotRequest\x12\x10\n\x08tenantId\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x0f\n\x07\x63ontext\x18\x03 \x01(\t\"E\n\x0f\x43opilotResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x11\n\treasoning\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x63tions\x18\x03 \x03(\t2\xe8\x02\n\x13IntelligenceService\x12]\n\x13GetAnalyticsSummary\x12\x1e.intelligence.AnalyticsRequest\x1a&.intelligence.AnalyticsSummaryResponse\x12R\n\x0bPushInsight\x12 .intelligence.PushInsightRequest\x1a!.intelligence.PushInsightResponse\x12S\n\x12GetRevenueForecast\x12\x1d.intelligence.ForecastRequest\x1a\x1e.intelligence.ForecastResponse\x12I\n\nAskCopilot\x12\x1c.intelligence.CopilotRequest\x1a\x1d.intelligence.CopilotResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'intelligence_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYTICSREQUEST']._serialized_start=36
  _globals['_ANALYTICSREQUEST']._serialized_end=86
  _globals['_ANALYTICSSUMMARYRESPONSE']._serialized_start=88
  _globals['_ANALYTICSSUMMARYRESPONSE']._serialized_end=210
  _globals['_PUSHINSIGHTREQUEST']._serialized_start=212
  _globals['_PUSHINSIGHTREQUEST']._serialized_end=318
  _globals['_PUSHINSIGHTRESPONSE']._serialized_start=320
  _globals['_PUSHINSIGHTRESPONSE']._serialized_end=369
  _globals['_FORECASTREQUEST']._serialized_start=371
  _globals['_FORECASTREQUEST']._serialized_end=420
  _globals['_FORECASTRESPONSE']._serialized_start=422
  _globals['_FORECASTRESPONSE']._serialized_end=504
  _globals['_COPILOTREQUEST']._serialized_start=506
  _globals['_COPILOTREQUEST']._serialized_end=575
  _globals['_COPILOTRESPONSE']._serialized_start=577
  _globals['_COPILOTRESPONSE']._serialized_end=646
  _globals['_INTELLIGENCESERVICE']._serialized_start=649
  _globals['_INTELLIGENCESERVICE']._serialized_end=1009
# @@protoc_insertion_point(module_scope)
